Repository Niche-538/UniGenie, pull requests merged in 2022-03, with the labels that each got.

#48 Form validation for 'Add University' form
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/AddUniversity.jsx
Labels: enhancement, difficulty: medium, Sprint 2

#50 feat(api): University api and db updates based on FrontEnd design
  .DS_Store
  server/.DS_Store
  server/db.sql
  server/main.go
  server/models/go.mod
  server/unigenie.db
Labels: type: feature, difficulty: easy, Sprint 2

#49 Modified add program/course form
  webapp/src/components/AddPrograms.jsx
  webapp/src/components/AddUniversity.jsx
Labels: enhancement, type: feature, difficulty: hard, Sprint 2

#52 feat(api): Setting up Unit Test Framework
  server/.vscode/launch.json
  server/main.go
  server/main_test.go
Labels: type: feature, difficulty: easy, Sprint 2

#54 feat(api): Test Cases for GET Apis get universities and getUsers
  server/.vscode/launch.json
  server/database/database_queries.sql
  server/database/go.mod
  server/db.sql
  server/main.go
  server/main_test.go
  server/models/database.go
  server/models/tpAPI.go
  server/routes/authRouter.go
  server/routes/userRouter.go
Labels: type: feature, difficulty: easy, Sprint 2

#55 feat(api): Adding Program, Courses tables in db
  server/database/database_queries.sql
  server/go.mod
  server/go.sum
  server/main.go
  server/main_test.go
  server/models/database.go
  server/models/tpAPI.go
  server/unigenie.db
Labels: difficulty: easy, Sprint 2

#56 feat(webapp): Navbar changed
  webapp/src/components/AdminLogin.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/Navigation_nonMain.jsx
  webapp/src/index.js
Labels: bug, type: bug, difficulty: hard, Sprint 2

#58 feat(webapp): connected front and back end
  .DS_Store
  package-lock.json
  package.json
  webapp/src/components/AddUniversity.jsx
  webapp/src/components/StudentSignup.jsx
  webapp/src/index.js
Labels: type: feature, difficulty: hard, Sprint 2

#59 Added university applications page for students
  webapp/src/components/AddUniversity.jsx
  webapp/src/components/AdminFunc.jsx
  webapp/src/components/AdminLogin.jsx
  webapp/src/components/AdminSignup.jsx
  webapp/src/components/Anim.tsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/StudentDetails.jsx
  webapp/src/components/StudentLogin.jsx
  webapp/src/components/StudentSignup.jsx
  webapp/src/components/UniversityApplications.jsx
  webapp/src/index.js
  webapp/src/styles.module.css
Labels: enhancement, type: feature, difficulty: easy, Sprint 2

#61 feat(API): Created Schemas for Student's Personal and Education Details
  server/controllers/userControllers.go
  server/main.go
  server/models/database.go
  server/unigenie.db
Labels: type: feature, difficulty: easy, Sprint 2

#62 Cypress E2E test for admin functionality page
  webapp/cypress.json
  webapp/cypress/downloads/downloads.html
  webapp/cypress/fixtures/example.json
  webapp/cypress/integration/AdminFunctionalitySpec.js
  webapp/cypress/plugins/index.js
  webapp/cypress/support/commands.js
  webapp/cypress/support/index.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/index.js
Labels: enhancement, type: feature, difficulty: medium, Sprint 2

#64 Cypress testing for add university page
  webapp/cypress/integration/AddUniversitySpec.js
  webapp/src/components/AddUniversity.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 2

#80 Modified landing page
  webapp/public/index.html
  webapp/src/components/Anim.tsx
  webapp/src/components/Icon.jsx
  webapp/src/components/LandingPage.jsx
  webapp/src/components/StudentDetails.jsx
  webapp/src/index.css
  webapp/src/index.js
  webapp/src/typings.d.ts
Labels: enhancement, difficulty: medium, Sprint 3

#83 feat(api): Adding User Preference Table
  server/database/database_queries.sql
  server/models/database.go
  server/models/userModel.go
  server/unigenie.db
Labels: difficulty: easy

#85 feat(api): Added User University Application Table and Post api for User Preferences and User University Application
  server/api/userAPI.go
  server/database/database_queries.sql
  server/models/database.go
  server/models/userModel.go
  server/unigenie.db
Labels: difficulty: medium, Sprint 3
