Repository Niche-538/UniGenie, pull requests merged in 2022-02, with the labels that each got.

#13 feat(api): Adding get universities api
  server/.DS_Store
  server/apiTest.go
  server/database.go
  server/main.go
  server/unigenie.db
Labels: type: feature, difficulty: medium, sprint 1

#14 feat(webapp): created admin functionality pages
  .vscode/settings.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUniversity.jsx
  webapp/src/components/AdminFunc.jsx
  webapp/src/components/AdminLogin.jsx
  webapp/src/components/AdminSignup.jsx
  webapp/src/components/DeleteUniversity.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/StudentLogin.jsx
  webapp/src/components/StudentSignup.jsx
  webapp/src/index.css
  webapp/src/index.js
  webapp/src/logo.svg
  webapp/src/reportWebVitals.js
  webapp/src/setupTests.js
Labels: type: feature, difficulty: medium, sprint 1

#11 feat(web app): Created page skeletons
  .vscode/settings.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AdminLogin.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/StudentLogin.jsx
  webapp/src/index.css
  webapp/src/index.js
  webapp/src/logo.svg
  webapp/src/reportWebVitals.js
  webapp/src/setupTests.js
Labels: type: feature, difficulty: medium, sprint 1

#16 Feature/UG5-1
  server/database.go
  server/main.go
  server/unigenie.db
Labels: difficulty: easy, sprint 1

#17 feat (webapp): Reupload index.js
  webapp/src/index.js
Labels: type: bug

#18 feat(api): Adding DB entries
  server/database.go
  server/unigenie.db
Labels: type: feature, difficulty: easy, sprint 1

#19 feat(api): Adding Get api from universities and users
  server/api.go
  server/apiTest.go
  server/database.go
  server/db.sql
  server/main.go
  server/unigenie.db
Labels: type: feature, difficulty: medium, sprint 1

#22 feat (webapp): Student Details Form Created
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/AdminFunc.jsx
  webapp/src/components/AdminLogin.jsx
  webapp/src/components/StudentDetails.jsx
  webapp/src/components/StudentSignup.jsx
  webapp/src/index.js
Labels: type: feature, difficulty: medium, sprint 1

#23 feat(api): Added POST API for adding users and universities
  .gitignore
  server/database.go
  server/main.go
  server/models/go.mod
  server/unigenie.db
Labels: type: feature, difficulty: medium, sprint 1

#24 feat(webapp): Created university add form
  webapp/src/components/AddUniversity.jsx
Labels: type: feature, difficulty: medium, sprint 1

#26 feature(webapp):beautification of landing page
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.tsx
  webapp/src/components/Icon.jsx
  webapp/src/index.css
  webapp/src/index.js
  webapp/src/styles.module.css
  webapp/src/typings.d.ts
Labels: difficulty: medium

#36 Modified student details form and add university form
  .gitignore
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/AddUniversity.jsx
  webapp/src/components/StudentDetails.jsx
Labels: enhancement, difficulty: medium, Sprint 2

#38 Minor functionality changes; React-Bootstrap instead of Bootstrap
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/components/AddPrograms.jsx
  webapp/src/components/AddUniversity.jsx
  webapp/src/components/AdminFunc.jsx
  webapp/src/components/AdminLogin.jsx
  webapp/src/components/AdminSignup.jsx
  webapp/src/components/DeleteUniversity.jsx
  webapp/src/components/Icon.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/StudentDetails.jsx
  webapp/src/components/StudentLogin.jsx
  webapp/src/components/StudentSignup.jsx
  webapp/src/index.js
Labels: enhancement, difficulty: easy, Sprint 2
