Repository Niche-538/UniGenie, pull requests merged in 2022-04, with the labels that each got.

#91 Created Student Home Page
  webapp/src/components/AdminSignup.jsx
  webapp/src/components/ProfilePage.jsx
  webapp/src/components/UniversityApplications.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 3

#92 Created student home page
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LandingPage.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/Navigation_nonMain.jsx
  webapp/src/components/StudentHomePage.jsx
  webapp/src/index.js
Labels: enhancement, type: feature, difficulty: hard, Sprint 3

#95 feat(webapp):modified landing page, changing color schema
  .DS_Store
  webapp/public/index.html
  webapp/src/components/Icon.jsx
  webapp/src/components/LandingPage.jsx
  webapp/src/components/Lp.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/icons8-magic-lamp-96.png
  webapp/src/components/landing.css
  webapp/src/index.js
Labels: enhancement, type: feature, difficulty: medium, Sprint 3

#96 feat(webapp): created modal sign up page
  webapp/src/components/Footerx.jsx
  webapp/src/components/Lp.jsx
  webapp/src/components/ProfilePage.jsx
  webapp/src/components/StudSignUp.jsx
  webapp/src/components/landing.css
  webapp/src/index.js
Labels: enhancement, type: feature, difficulty: medium, Sprint 3

#97 Changed color schema
  webapp/src/components/Footerx.jsx
  webapp/src/components/Lp.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/Navigation_nonMain.jsx
  webapp/src/components/ProfilePage.jsx
  webapp/src/components/ProfileSettingsPage.jsx
  webapp/src/components/StudentHomePage.jsx
  webapp/src/components/landing.css
  webapp/src/index.js
Labels: enhancement, type: feature, difficulty: easy, Sprint 3

#99 feat(webapp):implemented post for student signup
  server/unigenie.db
  webapp/src/components/Lp.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/Navigation_nonMain.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 3

#101 feat(webapp): sending encrypted password to backend
  server/unigenie.db
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Lp.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 3

#102 feat(api): Adding GET api for University applications and User preferences
  server/api/userAPI.go
  server/main.go
Labels: difficulty: medium, Sprint 3

#105 feat(api) : Adding unit test cases for the newly added api's
  server/main_test.go
  server/unigenie.db
Labels: type: feature, difficulty: easy, Sprint 3

#106 Updated Blog Page
  webapp/src/components/StudentHomePage.jsx
  webapp/src/components/landing.css
Labels: enhancement, type: feature, difficulty: easy, Sprint 3

#107 feat(API): Password hashing and JWT token generation
  server/auth/auth.go
  server/auth/auth_test.go
  server/controllers/universityController.go
  server/controllers/userControllers.go
  server/database/database.go
  server/database/databaseConnection.go
  server/go.mod
  server/go.sum
  server/helpers/authHelper.go
  server/main.go
  server/main_test.go
  server/models/models_test.go
  server/models/userModel.go
  server/routes/authRouter.go
  server/routes/userRouter.go
  server/unigenie.db
Labels: difficulty: hard, Sprint 3

#109 feat(API): Bug Fixes
  server/controllers/userControllers.go
  server/database/database_queries.sql
  server/go.mod
  server/main.go
  server/main_test.go
  server/models/database.go
  server/models/models_test.go
  server/models/userModel.go
  server/routes/authRouter.go
  server/routes/userRouter.go
  server/unigenie.db
Labels: bug, Sprint 3

#110 feat(API): Added CORS headers to resolve Cross-Origin issues
  .gitignore
  server/.env
  server/api/userAPI.go
  server/database/database_queries.sql
  server/go.mod
  server/go.sum
  server/main.go
  server/models/database.go
  server/models/universityModel.go
  server/models/userModel.go
  server/unigenie.db
Labels: enhancement, difficulty: easy, Sprint 4

#112 Adding sample Get.jsx file
  server/unigenie.db
  webapp/src/components/Get.jsx
  webapp/src/index.js
Labels: type: feature, difficulty: medium, Sprint 4

#113 updated Get.jsx file
  webapp/src/components/Get.jsx
  webapp/src/index.js
Labels: type: feature, difficulty: medium, Sprint 4

#114 changed index.js
  webapp/src/index.js
Labels: difficulty: easy, Sprint 4

#116 feature(webapp): structural changes
  server/unigenie.db
  webapp/src/App.js
  webapp/src/components/Get.jsx
  webapp/src/index.css
  webapp/src/index.js
Labels: enhancement, type: feature, difficulty: easy, Sprint 4

#119 Removed hamburger menu
  package-lock.json
  package.json
  webapp/src/App.js
  webapp/src/components/Dashboard.jsx
  webapp/src/components/Navigation_nonMain.jsx
  webapp/src/index.js
Labels: enhancement, type: feature, difficulty: easy, Sprint 4

#123 feat(webapp):Created resources pages
  webapp/src/App.js
  webapp/src/components/CS.jsx
  webapp/src/components/Canada.jsx
  webapp/src/components/MBA.jsx
  webapp/src/components/Mech.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/Navigation_nonMain.jsx
  webapp/src/components/Resources.jsx
  webapp/src/components/UK.jsx
  webapp/src/components/US.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#127 feat(api): Techincal Spike Story
  server/api/userAPI.go
  server/main.go
  server/unigenie.db
Labels: Sprint 4

#128 feat(webapp): updates CS.jsx
  webapp/src/components/CS.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#129 feature(webapp): Update US.jsx
  webapp/src/components/US.jsx
Labels: enhancement, type: feature, difficulty: easy, Sprint 4

#130 feat(webapp):Updates MBA.jsx
  webapp/src/components/MBA.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#131 feature(webapp): Updated UK.jsx
  webapp/src/components/UK.jsx
  webapp/src/components/US.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#132 feat(webapp):Updates CS.jsx
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/CS.jsx
  webapp/src/components/Mech.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#133 feat(webapp):updates mech.jsx
  webapp/src/components/CS.jsx
  webapp/src/components/MBA.jsx
  webapp/src/components/Mech.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#134 feature(webapp): Updated Canada.jsx
  webapp/src/components/Canada.jsx
  webapp/src/components/UK.jsx
  webapp/src/components/US.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#135 feature(webapp): Minor changes
  webapp/src/components/CS.jsx
  webapp/src/components/Canada.jsx
  webapp/src/components/MBA.jsx
  webapp/src/components/Mech.jsx
  webapp/src/components/UK.jsx
  webapp/src/components/US.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#136 fix(api): Fixing Get api's for university application and User Preferences
  server/api/userAPI.go
  server/main.go
Labels: type: bug, difficulty: easy, Sprint 4

#138 feat(api): Adding parameterized api and updating uni table
  server/api/userAPI.go
  server/database/database_queries.sql
  server/main.go
  server/unigenie.db
Labels: difficulty: medium, Sprint 4

#139 feat(webapp): updates Explore.jsx
  webapp/src/App.js
  webapp/src/components/Explore.jsx
  webapp/src/components/Get.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/Resources.jsx
  webapp/src/components/landing.css
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#140 feat(api): Adding countrywise api and db
  server/api/userAPI.go
  server/database/database_queries.sql
  server/main.go
  server/models/universityModel.go
  server/unigenie.db
Labels: difficulty: medium, Sprint 4

#141 feat(api): Moving uni api's to dedicated file
  server/api/universityAPI.go
  server/api/userAPI.go
Labels: enhancement, difficulty: easy

#142 feat(webapp):Updates Explore.js
  webapp/src/App.js
  webapp/src/components/Explore.jsx
  webapp/src/components/Get.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#143 feat(webapp):Updates Explore.js
  webapp/src/components/Explore.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#144 feat(api): Adding CS US unis for frontend testing
  server/database/database_queries.sql
  server/unigenie.db
Labels: difficulty: easy, Sprint 4

#145 feat(api): Populating US universities
  server/database/database_queries.sql
  server/unigenie.db
Labels: difficulty: easy, Sprint 4

#146 feat(webapp):Updates Explore.js
  server/.DS_Store
  webapp/src/App.js
  webapp/src/components/Explore.jsx
Labels: enhancement, type: feature, difficulty: easy, Sprint 4

#147 feature(webapp): Updates Dashboard.jsx
  webapp/src/components/Dashboard.jsx
  webapp/src/components/Get.jsx
  webapp/src/components/landing.css
Labels: enhancement, type: feature, difficulty: hard, Sprint 4

#148 feat(DB): Added UK and Canadian Universities to the DB
  server/database/database_queries.sql
  server/unigenie.db
Labels: enhancement, type: feature, difficulty: easy, Sprint 4

#149 feat(webapp):Updates StudentHomePage.jsx
  webapp/src/components/Get.jsx
  webapp/src/components/Lp.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/Navigation_nonMain.jsx
  webapp/src/components/StudentHomePage.jsx
Labels: enhancement, type: feature, difficulty: hard, Sprint 4

#153 feat(api): Adding db and api for Task feature
  server/api/userAPI.go
  server/database/database_queries.sql
  server/main.go
  server/models/userModel.go
  server/unigenie.db
Labels: difficulty: easy, Sprint 4

#154 feat(webapp): Updates StudentHomePage.jsx
  server/unigenie.db
  webapp/src/components/StudentHomePage.jsx
Labels: enhancement, type: feature, difficulty: hard, Sprint 4

#155 feat(webapp):Updates StudentHomePage
  server/unigenie.db
  webapp/src/components/AddUniversity.jsx
  webapp/src/components/Lp.jsx
  webapp/src/components/StudentHomePage.jsx
Labels: enhancement, type: feature, difficulty: hard, Sprint 4

#156 Updates StudentHomePage.jsx
  webapp/src/components/StudentHomePage.jsx
Labels: enhancement, type: bug, difficulty: medium, Sprint 4

#159 feature(webapp): Updates Navigation_nonMain.jsx
  webapp/src/components/Explore.jsx
  webapp/src/components/Navigation_nonMain.jsx
  webapp/src/components/ProfilePage.jsx
  webapp/src/components/ProfileSettingsPage.jsx
  webapp/src/components/StudentHomePage.jsx
Labels: enhancement, type: feature, difficulty: easy, Sprint 4

#160 feat(api): Adding Post api for Tasks
  server/api/userAPI.go
  server/database/database_queries.sql
  server/models/userModel.go
  server/unigenie.db
Labels: type: feature, difficulty: easy, Sprint 4

#162 feat(webapp):Updates AuthHeader.js and LP.jsx
  package-lock.json
  package.json
  webapp/src/components/AuthHeader.js
  webapp/src/components/Lp.jsx
Labels: enhancement, type: feature, difficulty: hard, Sprint 4

#163 feature(webapp): Created Login.jsx
  server/unigenie.db
  webapp/src/components/Login.jsx
  webapp/src/components/Lp.jsx
Labels: enhancement, type: feature, difficulty: easy, Sprint 4

#164 feature(webapp): Structural changes
  webapp/src/App.js
  webapp/src/components/AddUniversity.jsx
  webapp/src/components/AdminFunc.jsx
  webapp/src/components/AdminLogin.jsx
  webapp/src/components/AdminSignup.jsx
  webapp/src/components/AuthHeader.js
  webapp/src/components/Canada.jsx
  webapp/src/components/DeleteUniversity.jsx
  webapp/src/components/Explore.jsx
  webapp/src/components/Get.jsx
  webapp/src/components/LandingPage.jsx
  webapp/src/components/Lp.jsx
  webapp/src/components/Navigation.jsx
  webapp/src/components/ProfilePage.jsx
  webapp/src/components/ProfileSettingsPage.jsx
  webapp/src/components/StudSignUp.jsx
  webapp/src/components/StudentDetails.jsx
  webapp/src/components/StudentLogin.jsx
  webapp/src/components/StudentSignup.jsx
  webapp/src/components/UK.jsx
  webapp/src/components/US.jsx
  webapp/src/components/UniversityApplications.jsx
  webapp/src/components/footer.jsx
  webapp/src/components/navigationNonMain.jsx
Labels: documentation, difficulty: easy, Sprint 4

#166 feat(webapp): updates login.jsx, created auth.js and userData.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/auth.js
  webapp/src/components/login.jsx
  webapp/src/components/userData.js
Labels: enhancement, type: feature, difficulty: hard, Sprint 4

#167 feature(webapp): Update login.jsx
  webapp/src/components/login.jsx
Labels: enhancement, type: feature, difficulty: hard, Sprint 4

#169 feat(webapp): Updates landingPage.jsx
  webapp/src/components/landingPage.jsx
  webapp/src/components/login.jsx
Labels: bug, type: bug, difficulty: medium, Sprint 4

#170 feat(api): Adding Test Cases for Task api's and University Api's
  server/main.go
  server/main_test.go
Labels: type: feature, difficulty: easy, Sprint 4

#171 feat(API): Added POST API for Blogs
  server/api/userAPI.go
  server/auth/auth.go
  server/auth/auth_test.go
  server/controllers/userControllers.go
  server/database/database.go
  server/database/database_queries.sql
  server/helpers/authHelper.go
  server/helpers/tokenHelper.go
  server/main.go
  server/middleware/authMiddleware.go
  server/models/userModel.go
  server/routes/authRouter.go
  server/routes/userRouter.go
  server/test/post_test.go
  server/unigenie.db
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#173 feature(webapp): Update studentHomePage.jsx
  webapp/src/components/studentHomePage.jsx
Labels: enhancement, type: feature, difficulty: hard, Sprint 4

#174 feat(webapp): updates studentHomePage.jsx
  .gitignore
  server/unigenie.db
  webapp/src/App.js
  webapp/src/components/studentHomePage.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#175 feature(webapp): Updates landingPage.jsx
  server/unigenie.db
  webapp/src/App.js
  webapp/src/components/landingPage.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#178 fix(api): Fixing Post user university application and updating Test cases
  server/main.go
  server/main_test.go
  server/unigenie.db
Labels: bug, enhancement, difficulty: easy

#180 feat(webapp): Updates studentHomePage.jsx
  server/database/database_queries.sql
  webapp/src/components/studentHomePage.jsx
Labels: type: feature, difficulty: medium, Sprint 4

#181 feat(api): Populating universities table
  server/database/database_queries.sql
  server/unigenie.db
Labels: difficulty: easy, Sprint 4

#182 feature(webapp): Updates profileSettingsPage.jsx
  webapp/src/components/landing.css
  webapp/src/components/profilePage.jsx
  webapp/src/components/profileSettingsPage.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#183 feature(webapp): Update profilePage.jsx
  webapp/src/components/profilePage.jsx
Labels: enhancement, type: feature, difficulty: medium, Sprint 4

#186 feat(API): Testing for APIs
  server/auth/auth.go
  server/auth/auth_test.go
  server/main_test.go
  server/unigenie.db
Labels: type: feature, difficulty: easy, Sprint 4
